### ISSUE TITLE
bug? extra 0: in the timecode

### ISSUE THREAD

**Issue by moonwalkerstalker** [azhuge233/ConsoleWhisper#6]
Hello!
I've managed to create a batch script to run various videos in a sequence and create the .srt of those videos. 
It works great!

When I try to import the srt to my video editing software it does not work
I checked the srt file and it goes with an extra '0:' at the start of each timecode like this --> 0:00:00:00,0000000 --> 0:00:00:04,0000000
after I remove the '0:' from the start of each timecode the srt file works great
like this: 
00:00:00,0000000 --> 00:00:04,0000000

don't know why the extra 0 came out, I tryed looking at the code but did not find where to fix it

**Comment by azhuge233** [comment]
Yes, this is a bug. I didn't notice that the timecode format was non-standard for SubRip files.
Fixed in the new [commit](https://github.com/azhuge233/ConsoleWhisper/commit/0b04d4b55f1395de73a693d76e40860dad8c6fa5), the latest release should now be working.

Thank you for the feedback!
